---
- name: Ansible Playbook to update host, install and run Docker
  hosts: all
  become: yes
  tasks:
  - name: Update host and install Docker
    shell: update.sh
    path: /vagrant
  - name: Install pip
    apt: name=python-pip state=present
  - name: install docker-py package
    pip: name=docker-py
  - name: Build Docker image from Dockerfile
    docker_image:
      name: alpinetry
      path: /vagrant
      state: build
  - name: Run the container
    docker_container:
      image: alpinetry:latest
      path: /vagrant
      state: running